export type ToolHelp = {
  title: string;
  eyebrow: string;
  purpose: string;
  example: string;
  how: string;
  aiPrepares: string;
  teamValidates: string;
  nextSteps: string;
};

export const toolHelpByPath: Record<string, ToolHelp> = {
  "/dashboard": {
    title: "Tableau de bord",
    eyebrow: "Lire la maquette",
    purpose: "Cette page sert de point de départ pour comprendre ce que la maquette montre à New Ingenia.",
    example: "Un client écrit, une offre doit être préparée, une information technique est recherchée, puis une action est suivie.",
    how: "La page regroupe les cas concrets et donne un ordre de présentation simple pour le rendez-vous.",
    aiPrepares: "Des résumés, des brouillons, des suggestions d'action et des aperçus utiles pour gagner du temps.",
    teamValidates: "L'équipe garde la décision finale : elle relit, corrige, complète et choisit la suite.",
    nextSteps: "Il faudrait connecter les emails, les documents, les offres, les projets et les données clients existantes.",
  },
  "/dashboard/demo": {
    title: "Parcours de présentation",
    eyebrow: "Rendez-vous client",
    purpose: "Cette page aide à présenter la maquette dans un ordre logique, sans naviguer au hasard.",
    example: "Un client demande trois postes de travail NI'One, l'équipe prépare une offre puis suit la relance.",
    how: "Chaque étape ouvre une page précise et montre ce que l'utilisateur peut faire à ce moment-là.",
    aiPrepares: "Un fil de démonstration, des exemples de livrables et des transitions faciles à expliquer.",
    teamValidates: "La personne qui présente choisit les étapes utiles selon le temps disponible et les questions du client.",
    nextSteps: "Il faudrait adapter le parcours aux vrais processus commerciaux et techniques de New Ingenia.",
  },
  "/dashboard/demandes-entrantes": {
    title: "Demandes entrantes",
    eyebrow: "Demande client",
    purpose: "Ce module aide à comprendre rapidement une demande reçue par email ou formulaire.",
    example: "Un client demande trois postes de travail pour une ligne horlogère avec surface ESD, éclairage et rangements.",
    how: "L'utilisateur ouvre la demande. L'outil résume le besoin, repère les informations manquantes et propose la prochaine action.",
    aiPrepares: "Résumé du besoin, questions à poser, brouillon de réponse et base pour créer une offre.",
    teamValidates: "Le commercial vérifie le besoin, complète les informations et décide de la suite.",
    nextSteps: "Il faudrait connecter la boîte email, le formulaire du site, le CRM et le module d'offres.",
  },
  "/dashboard/recherche-docs": {
    title: "Recherche technique",
    eyebrow: "Document technique",
    purpose: "Ce module aide à retrouver rapidement une information fiable dans les documents techniques.",
    example: "Un technicien cherche quelle structure choisir pour un poste de travail modulaire avec charge élevée et surface ESD.",
    how: "L'utilisateur pose une question. L'outil retrouve les passages utiles et affiche le document source.",
    aiPrepares: "Une réponse courte, les références utiles et les sources à ouvrir pour vérifier.",
    teamValidates: "Le technicien confirme la référence, la charge, les contraintes et l'application client.",
    nextSteps: "Il faudrait connecter les catalogues, fiches NI'One, notices fournisseurs et anciennes offres.",
  },
  "/dashboard/redaction-offres": {
    title: "Offres clients",
    eyebrow: "Offre client",
    purpose: "Ce module aide à structurer une offre à partir d'une demande client.",
    example: "Offre pour trois postes NI'One destinés à une ligne d'assemblage horlogère.",
    how: "L'utilisateur complète les informations importantes, choisit les options et visualise une base d'offre.",
    aiPrepares: "Structure d'offre, texte commercial, options techniques, prochaines étapes et email d'envoi.",
    teamValidates: "Le commercial et le technique vérifient les prix, les délais, les options et les conditions.",
    nextSteps: "Il faudrait connecter les tarifs, modèles d'offres, stocks, historiques clients et validations internes.",
  },
  "/dashboard/facturation": {
    title: "Facturation",
    eyebrow: "Facture",
    purpose: "Ce module aide à préparer une facture claire à partir d'une offre ou d'un projet terminé.",
    example: "Facture issue d'une offre validée pour postes de travail modulaires NI'One.",
    how: "L'utilisateur indique la source, vérifie les lignes, ajuste les montants et consulte l'aperçu.",
    aiPrepares: "Lignes de facture, libellés lisibles, totaux et brouillon prêt à relire.",
    teamValidates: "L'équipe vérifie les montants, la TVA, les conditions de paiement et la référence commande.",
    nextSteps: "Il faudrait connecter les offres validées, les projets livrés et le logiciel de facturation.",
  },
  "/dashboard/redaction-emails": {
    title: "Emails clients",
    eyebrow: "Email client",
    purpose: "Ce module aide à rédiger un email professionnel sans repartir de zéro.",
    example: "Email d'envoi d'offre à un client horloger après validation d'une configuration NI'One.",
    how: "L'utilisateur choisit le contexte, précise le message important puis relit le brouillon.",
    aiPrepares: "Objet, corps de message, ton adapté, rappel des points importants et signature.",
    teamValidates: "L'équipe vérifie le contenu, les délais, les pièces jointes et le ton avant envoi.",
    nextSteps: "Il faudrait connecter les contacts, les offres, les pièces jointes et la messagerie.",
  },
  "/dashboard/triage-emails": {
    title: "Priorisation emails",
    eyebrow: "Boîte email",
    purpose: "Ce module aide à repérer les emails urgents, les demandes clients et les messages à transformer en action.",
    example: "Un email demande un devis rapide pour une ligne complète de postes de travail.",
    how: "Les messages sont classés par priorité. L'utilisateur ouvre d'abord ce qui demande une action.",
    aiPrepares: "Priorité, catégorie, résumé court et action proposée pour chaque email.",
    teamValidates: "L'équipe confirme ce qui est urgent, ce qui peut attendre et ce qui doit être archivé.",
    nextSteps: "Il faudrait connecter Outlook ou Gmail, les contacts, les projets et les règles internes.",
  },
  "/dashboard/linkedin": {
    title: "Communication LinkedIn",
    eyebrow: "Communication",
    purpose: "Ce module aide à transformer une idée, un projet ou une photo en brouillon de publication.",
    example: "Publication sur un poste NI'One livré pour un environnement de précision.",
    how: "L'utilisateur décrit le contexte, indique l'objectif puis relit le brouillon proposé.",
    aiPrepares: "Texte de post, accroche, hashtags et angle de communication professionnel.",
    teamValidates: "L'équipe valide le fond, les noms cités, les photos, le ton et la date de publication.",
    nextSteps: "Il faudrait connecter la bibliothèque média, le calendrier éditorial et la page LinkedIn entreprise.",
  },
  "/dashboard/fiches-clients": {
    title: "Fiches clients",
    eyebrow: "Client",
    purpose: "Ce module aide à retrouver rapidement ce qui s'est passé avec un client.",
    example: "Historique d'un client horloger avec offres, projets NI'One, réunions et relances.",
    how: "L'utilisateur ouvre une fiche et voit les contacts, projets, offres et dernières interactions.",
    aiPrepares: "Résumé client, points ouverts, relances à faire et contexte utile avant appel.",
    teamValidates: "L'équipe corrige les informations, confirme les prochaines actions et garde l'historique propre.",
    nextSteps: "Il faudrait connecter le CRM, les emails, les offres, les factures et les notes commerciales.",
  },
  "/dashboard/studio-visuel": {
    title: "Studio 3D",
    eyebrow: "Aperçu 3D",
    purpose: "Ce module aide à montrer rapidement une idée visuelle pour aider un client à se projeter.",
    example: "Aperçu d'un poste NI'One personnalisé pour discuter de la configuration avec le client.",
    how: "L'utilisateur choisit un produit, ajuste la vue et montre l'aperçu pendant l'échange.",
    aiPrepares: "Une base visuelle, des vues utiles et des supports à intégrer dans une offre ou une présentation.",
    teamValidates: "Le technique vérifie que l'idée reste réaliste, conforme et utile pour le client.",
    nextSteps: "Il faudrait connecter les modèles produits, les options, les plans et les données de configuration.",
  },
  "/dashboard/studio-marketing": {
    title: "Studio Marketing",
    eyebrow: "Visuel produit",
    purpose: "Ce module aide à préparer une image ou une idée de visuel pour une offre, LinkedIn ou une présentation client.",
    example: "Visuel d'un poste NI'One dans un atelier horloger moderne.",
    how: "L'utilisateur choisit le produit, l'usage, le style et vérifie le visuel principal.",
    aiPrepares: "Brief visuel, proposition d'image, message à transmettre et supports possibles.",
    teamValidates: "L'équipe valide le rendu, la fidélité produit, le contexte et l'usage commercial.",
    nextSteps: "Il faudrait connecter les photos produits, la charte, les modèles visuels et les canaux de diffusion.",
  },
  "/dashboard/reunion-ia": {
    title: "Réunion",
    eyebrow: "Réunion",
    purpose: "Ce module aide à transformer des notes de réunion en résumé, décisions et tâches.",
    example: "Réunion client sur validation d'une configuration NI'One et délai de livraison.",
    how: "L'utilisateur colle des notes. L'outil sépare le contexte, les décisions et les actions à suivre.",
    aiPrepares: "Résumé, décisions, liste de tâches, responsables et email de compte-rendu.",
    teamValidates: "Les participants confirment les décisions, les dates, les responsables et les messages à envoyer.",
    nextSteps: "Il faudrait connecter les agendas, comptes-rendus, projets, tâches et emails.",
  },
  "/dashboard/taches": {
    title: "Tâches",
    eyebrow: "Actions",
    purpose: "Ce module centralise les tâches issues des demandes, emails, réunions et projets.",
    example: "Relancer un client horloger après l'envoi d'une offre pour trois postes NI'One.",
    how: "Chaque tâche indique sa source, son échéance, son statut et le module à ouvrir.",
    aiPrepares: "Actions proposées, priorité, contexte et lien vers la page utile.",
    teamValidates: "Chaque personne confirme ce qu'elle prend en charge et met à jour l'avancement.",
    nextSteps: "Il faudrait connecter les projets, emails, réunions, offres et notifications internes.",
  },
  "/dashboard/veille": {
    title: "Veille",
    eyebrow: "Veille",
    purpose: "Ce module aide à regrouper les nouveautés fournisseurs, salons, tendances ou opportunités à surveiller.",
    example: "Nouveau catalogue fournisseur ou salon industriel utile pour les projets New Ingenia.",
    how: "Les informations importantes sont résumées en blocs courts avec une action possible.",
    aiPrepares: "Résumé, impact possible, opportunité, risque et document à conserver.",
    teamValidates: "La direction ou l'équipe commerciale choisit ce qui mérite une action.",
    nextSteps: "Il faudrait connecter les sources fournisseurs, salons, newsletters et dossiers documentaires.",
  },
  "/dashboard/gestion-roles": {
    title: "Accès & rôles",
    eyebrow: "Accès",
    purpose: "Ce module aide à définir qui peut voir ou modifier les informations selon son rôle.",
    example: "Un technicien peut consulter les documents et la 3D, mais pas modifier les droits ou la facturation.",
    how: "La matrice montre les pages accessibles pour chaque profil.",
    aiPrepares: "Une lecture claire des droits et des incohérences possibles.",
    teamValidates: "L'administrateur confirme les rôles, les exceptions et les droits sensibles.",
    nextSteps: "Il faudrait connecter l'annuaire, l'authentification, les rôles internes et les journaux d'accès.",
  },
  "/dashboard/parametres": {
    title: "Régler la maquette",
    eyebrow: "Paramètres",
    purpose: "Cette page regroupe les préférences utiles pour présenter ou tester la maquette.",
    example: "Changer le rôle affiché pour montrer ce que voit un admin, un manager ou un technicien.",
    how: "L'utilisateur ajuste les préférences visibles dans le navigateur.",
    aiPrepares: "Aucun contenu métier ici : la page sert surtout à tester l'expérience.",
    teamValidates: "La personne qui présente choisit les réglages adaptés au rendez-vous.",
    nextSteps: "Il faudrait connecter les vrais profils, préférences et paramètres d'organisation.",
  },
};

export function getToolHelp(pathname: string): ToolHelp | undefined {
  if (toolHelpByPath[pathname]) return toolHelpByPath[pathname];
  const normalized = pathname.replace(/\/$/, "");
  return toolHelpByPath[normalized];
}
